name: Django

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: pip install -r requirements.txt
    - run: python manage.py makemigrations LegacySite
    - run: python manage.py migrate
    - run: python manage.py shell -c 'import import_dbs' 
    - run: python manage.py test